Nepilsoņu vecumstruktūra Latvijā - 1-gada histogramma
-----

[Uz sākumu](http://www.demografija.lv)

* **Anotācija:** Dots pilsoņu un nepilsoņu skaits atkarībā no dzimšanas gada. 
Izveidot histogrammu, kas attēlotu nepilsoņu skaitu vecuma intervālos, intervāla garums 1 gads. 
* **Pārskata šablons:** [age-histogram1.rmd](age-histogram5.rmd)
* **Datu pirmavots:** [Iedzīvotāju reģistra statistika](http://www.pmlp.gov.lv/lv/sakums/statistika/iedzivotaju-registrs/)
* **Tabulveida dati:** [DzGads-VPd-2007_2014.csv](DzGads-VPd-2007_2014.csv)
* **Iegūtā diagramma:** [age-histogram1-anim.gif](figure-static/age-histogram1-anim.gif)
* **Saistītie raksti:** [Pilsoņu-nepilsoņu vecuma piramīda](population-pyramid.html)

Šajā histogrammā ikviens stabiņš apzīmē nepilsoņu skaitu attiecīgajā vecumā (gados) - savukārt visi nepilsoņi, kam ir 100 un vairāk gadu, ir apvienoti vienā stabiņā. Formāli runājot, mēs sadalām nenegatīvos skaitļus (visus iespējamos cilvēku vecumus gados) 101 savstarpēji nešķeļošos intervālos: $[0,1) \cup [1,2) \cup \ldots \cup [99,100) \cup [100,+\infty)$. Pēc tam saskaitām nepilsoņus, kuru vecumi atrodas katrā no šiem intervāliem. 

Ja PMLP pārskata datums ir kāda gada pirmais janvāris, tad sadalījums intervālos atbilst nepilsoņu dzimšanas gadiem. Piemēram, ja izvēlamies datumu 2014-01-01, tad visi 2013.gadā dzimušie ir 0 gadu veci jeb pieder intervālam $[0,1)$, utt. Savukārt, ja PMLP pārskata datums ir kāda gada pirmais jūlijs, tad izdarām pieņēmumu, ka ikvienā gadā dzimušie ir aptuveni vienādi sadalīti pa mēnešiem. Piemēram, ja izvēlamies datumu 2013-07-01, tad puse no 2012.gadā dzimušajiem uz 2013.g. 1.jūliju jau bija 1 gadu veci (gada pirmajā pusē dzimušie), savukārt otra puse no 2012.gadā dzimušajiem jāuzskata par 0 gadus veciem. 


### Animēta histogramma

Sekojošā attēlā histogrammas mainās ik pēc 0.75 sekundēm - sākot no pārskata datuma "2007-01-01", "2007-07-01", "2008-01-01", ..., "2014-01-01" (pavisam kopā 15 histogrammas). Pēdējais attēls paliek 3.75 sekundes; pēc tam animācija atkārtojas. Animētā GIF veidošanai lietots rīks Imagemagick. 

```{r results='hide', warning=FALSE, error=FALSE, message=FALSE}
# Set this path to the one that contains CSV data file
setwd("/home/st/demografija-lv/age-distribution/")

if (!"animation" %in% installed.packages()) install.packages("animation")
library(animation)

getYear <- function(x) round(1970+as.numeric(as.Date(x))/365.25, digits=1)
df <- read.csv("DzGads-VPd-2007_2014.csv")
getSlices <- function(reportDate) {
  cnt <- df[df$ReportDate==reportDate,"LvNonCitizens"]
  if (getYear(reportDate) == floor(getYear(reportDate))) {
    c(cnt[1:100], sum(cnt[101:length(cnt)]))
  }
  else {
    c(cnt[1] + 0.5*cnt[2], 
      0.5*(cnt[2:100] + cnt[3:101]), 
      0.5*cnt[101] + sum(cnt[102:length(cnt)]))
  }
}

dsets <- c("2007-01-01", "2007-07-01", "2008-01-01", "2008-07-01", 
           "2009-01-01", "2009-07-01", "2010-01-01", "2010-07-01", 
           "2011-01-01", "2011-07-01", "2012-01-01", "2012-07-01", 
           "2013-01-01", "2013-07-01", "2014-01-01")
# this call creates animated GIF (prerequisite: Imagemagick)
saveGIF({
  for (dset in dsets) {
    slices <- getSlices(dset)
    barplot(slices, 
            col="pink",space=0, ylim=c(0,8500),
            xlab="Age", ylab="Count of non-citizens")
    # define semi-transparent color
    lbRGB <- col2rgb("lightblue1")/255
    newLightgray <- rgb(lbRGB[1],lbRGB[2],lbRGB[3],0.3)
    # draw semi-transparent rectangles to create vertical bars
    rect(20*0:5,rep(0,6),10+20*0:5,8500,col=newLightgray, border=NA)
    # create grid and horizontal axis with labels
    grid(nx=NA, ny=NULL)
    midpts <- c(as.character(5*0:19),"100+")
    midptsShifted <- 0.5 + 5*0:20
    axis(1, at = midptsShifted, labels=midpts, cex.axis=0.9)
    # Print report date
    text(5, 7800, labels = dset, col="darkgray", 
         font=2)  
    text(95, 7800, labels = as.character(round(sum(slices))), col="red", font=2)
  }
}, movie.name = "age-histogram1-anim.gif", 
interval = c(rep(0.75,times=14),3.75), nmax = 30, ani.width = 600, 
ani.height = 450)
```




拉脱维亚“非公民”的年龄构成：一年的直方图 — Non-citizen age structure in Latvia: 1-year histogram  
*This report is available under a [Creative Commons License](http://creativecommons.org/licenses/by/4.0/deed.en_US)*